name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout code
    - name: Run all unit tests
      run: test/all_tests.sh
    - name: Dockerfile linting
      run: |
        # Install hadolint
        wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64 &&\
          chmod +x hadolint
        # Run linting
        ./hadolint test/do_lint.sh
